---
- name: loopr playbook
  hosts: all
  become: yes
  tasks:
    - name: install multiple softwares
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - git
        - tree
