#TAGS: To execute or skip specific tasks

- name: first playbook
  hosts: all
  tasks:
    - name: installing git
      yum:
       name: git
       state: present
      tags: a
    - name: installing httpd
      yum:
        name: maven
        state: present
      tags: b
    - name: create user
      user:
        name: test
        state: present
      tags: c    

#SINGLE TAG: ansible-playbook name.yml --tags a
#MULTI TAG: ansible-playbook name.yml --tags b,c
#SKIP TAG: ansible-playbook name.yml --skip-tags "c"
#MULTI SKIP TAGS: ansible-playbook name.yml --skip-tags "c,d"


